WIP: Enhancement grammatical edits
ReproNim/module-reproducible-basics pull request #3
Opened 2017-02-09 01:32 UTC by rbuccigrossi

This pull includes grammatical edits on the lesson (starting with 01-shell-basics). 

I'm pushing this as a Work In Progress so that you can review it and make sure I'm doing the right thing :)

2017-02-09 16:40 UTC, yarikoptic requested changes
getting pulled to switch, will finish reviewing later - but here are some comments ;)

2017-02-09 16:40 UTC, yarikoptic commented on CONTRIBUTING.md
> +which will generate and serve the lessons on <http://localhost:4000>.
indeed!  although might be worth  to be introduced as well to
http://github.com/ReproNim/module-template
on which one this one is based

2017-02-09 16:40 UTC, yarikoptic commented on _episodes/01-shell-basics.md
> + error-prone, and thus more reproducible."
as you might have noted, me is "greedy" (and somewhat consistent) on trailing periods if some other separator is used and it is clear that statement is 'done'.  That is why in this case, as well as among Objectives, I did not use trailing period.  In general -- I do not care much but OCD-me likes to be consistent

2017-02-09 16:40 UTC, yarikoptic commented on _episodes/01-shell-basics.md
> +  arbitrary set of commands. This will avoid manual retyping of the
why `will` here? all the other statements are "in present" tense statements of the facts ;)

2017-02-09 16:40 UTC, yarikoptic commented on _episodes/01-shell-basics.md
> +review a few aspects t particularly relate to reproducibility, as
it is always valuable to review `git diff` or better `git diff --color-words` in this case before committing ;)

2017-02-09 17:18 UTC, rbuccigrossi commented on _episodes/01-shell-basics.md
> + error-prone, and thus more reproducible."
Hmmm... git makes it a bit harder for you to accept changes you like.  But I can't leave sentences without periods :)

2017-02-09 17:24 UTC, rbuccigrossi commented on _episodes/01-shell-basics.md
> +  arbitrary set of commands. This will avoid manual retyping of the
Bah. I split the sentence, and went through a couple of iterations of changes, leaving the tense incorrect.

2017-02-09 17:26 UTC, rbuccigrossi commented on _episodes/01-shell-basics.md
> + error-prone, and thus more reproducible."
The other issue is that in order to make the key points easier to read, I split a couple into multiple sentences. But then not having a period at the end of the last sentence looks odd, and then I felt compelled to add periods at the end of the rest of the key points in order to have parallel structure.

2017-02-09 17:32 UTC, rbuccigrossi commented on _episodes/01-shell-basics.md
> +review a few aspects t particularly relate to reproducibility, as
Hmmm... I'm trying to go further and use "Remarkable" with a spell checker, but it doesn't seem to be completely reliable.

2017-02-09 18:40 UTC, rbuccigrossi commented on _episodes/01-shell-basics.md
> + error-prone, and thus more reproducible."
OK. I removed the periods and separated the sentences with a semicolon.  BTW, git diff --color-words is wonderful.

2017-02-10 19:48 UTC, yarikoptic commented on _episodes/01-shell-basics.md
> + error-prone, and thus more reproducible."
yeah -- saw semicolons ;-)  I will let them be although I would have just kept periods interim sentences.
you might then like also following aliases. 
```
    wdiff = diff --color-words
    pdiff = diff 'HEAD@{1}'
    pdfdiff = difftool -x diffpdf --no-prompt
    niidiff = difftool -x niidiff --no-prompt
    kompare = difftool -x kompare --no-prompt
    nbdiff = difftool -x nbdiff --no-prompt
```
I do use kompare also from time to time if I want quick GUI view and there is not that many files changed

2017-02-10 21:28 UTC, yarikoptic commented on index.md
> +embrace reproducibility as a principle to apply to your day-to-day
lovely!

2017-02-10 21:29 UTC, yarikoptic approved these changes

2017-02-10 21:29 UTC, merged